version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: 'unless-stopped'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p 5432
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pg/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - pg:/var/lib/postgresql/data

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005

  nginx:
    image: nginx
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_CLIENT=${DN_CLIENT:-domen}
      - DOMAIN_BACKEND=${DN_BACKEND:-domen}
    env_file:
      - .env
    volumes:
      - ./nginx-templates/templates:/etc/nginx/templates/
      - ~/../etc/letsencrypt:/etc/letsencrypt/
      - ./data:/etc/nginx/var/www/data/
    network_mode: host

volumes:
  pg:
